name: mm_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  sqflite: ^2.3.0
  intl: ^0.17.0
  anim_search_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "notepad.png" 
  android: true
  ios: true
